db.url=jdbc:mysql://localhost:3306/gestion_activos_tecnologicos?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
db.user=root
db.password=SamuelR29*
db.driver=com.mysql.cj.jdbc.Driver
